name: sheets_store
description: A simple package that allows you to use Google Sheets as cloud storage for your app.
version: 2.1.1
repository: https://github.com/Paty007gr/sheets_store

topics:
  - server
  - database
  - spreadsheets
  - cloud
  - google

environment:
  sdk: ^3.8.0

dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0